services:
  njs_postgres:
    container_name: njs_postgres
    image: postgres:16.13
    restart: always
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - test

  njs_pgadmin:
    image: dpage/pgadmin4
    container_name: njs_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8888:80
    user: "${UID}:${GID}"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - njs_postgres
    networks:
      - test

networks:
  test:
