"""Added AuthSession table

Revision ID: c8c646263e66
Revises: 9a42831ccd17
Create Date: 2026-07-11 14:43:13.205789

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c646263e66'
down_revision: Union[str, Sequence[str], None] = '9a42831ccd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authsession', 'user_agent')
    # ### end Alembic commands ###
