"""Added AuthSession table

Revision ID: 760349908ca0
Revises: c8c646263e66
Create Date: 2026-07-11 14:45:57.780759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760349908ca0'
down_revision: Union[str, Sequence[str], None] = 'c8c646263e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authsession', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
